export type CountryMeta = {
    tier : number;
    name : string;
    flag : string;
}

export const countriesData: Record<string, CountryMeta> = {
    // Tier 1 Countries
    "AU": { tier: 1, name: "Australia", flag: "🇦🇺" },
    "AT": { tier: 1, name: "Austria", flag: "🇦🇹" },
    "BE": { tier: 1, name: "Belgium", flag: "🇧🇪" },
    "CA": { tier: 1, name: "Canada", flag: "🇨🇦" },
    "DK": { tier: 1, name: "Denmark", flag: "🇩🇰" },
    "FI": { tier: 1, name: "Finland", flag: "🇫🇮" },
    "FR": { tier: 1, name: "France", flag: "🇫🇷" },
    "DE": { tier: 1, name: "Germany", flag: "🇩🇪" },
    "IE": { tier: 1, name: "Ireland", flag: "🇮🇪" },
    "IT": { tier: 1, name: "Italy", flag: "🇮🇹" },
    "LU": { tier: 1, name: "Luxembourg", flag: "🇱🇺" },
    "NL": { tier: 1, name: "Netherlands", flag: "🇳🇱" },
    "NZ": { tier: 1, name: "New Zealand", flag: "🇳🇿" },
    "NO": { tier: 1, name: "Norway", flag: "🇳🇴" },
    "ES": { tier: 1, name: "Spain", flag: "🇪🇸" },
    "SE": { tier: 1, name: "Sweden", flag: "🇸🇪" },
    "CH": { tier: 1, name: "Switzerland", flag: "🇨🇭" },
    "GB": { tier: 1, name: "United Kingdom", flag: "🇬🇧" },
    "US": { tier: 1, name: "United States of America", flag: "🇺🇸" },
    "JP": { tier: 1, name: "Japan", flag: "🇯🇵" },

    // Tier 2 Countries
    "AD": { tier: 2, name: "Andorra", flag: "🇦🇩" },
    "AR": { tier: 2, name: "Argentina", flag: "🇦🇷" },
    "BS": { tier: 2, name: "Bahamas", flag: "🇧🇸" },
    "BY": { tier: 2, name: "Belarus", flag: "🇧🇾" },
    "BO": { tier: 2, name: "Bolivia", flag: "🇧🇴" },
    "BA": { tier: 2, name: "Bosnia and Herzegovina", flag: "🇧🇦" },
    "BR": { tier: 2, name: "Brazil", flag: "🇧🇷" },
    "BN": { tier: 2, name: "Brunei", flag: "🇧🇳" },
    "BG": { tier: 2, name: "Bulgaria", flag: "🇧🇬" },
    "CL": { tier: 2, name: "Chile", flag: "🇨🇱" },
    "CN": { tier: 2, name: "China", flag: "🇨🇳" },
    "CO": { tier: 3, name: "Colombia", flag: "🇨🇴" },
    "CR": { tier: 2, name: "Costa Rica", flag: "🇨🇷" },
    "HR": { tier: 2, name: "Croatia", flag: "🇭🇷" },
    "CY": { tier: 2, name: "Cyprus", flag: "🇨🇾" },
    "CZ": { tier: 2, name: "Czech Republic", flag: "🇨🇿" },
    "DO": { tier: 2, name: "Dominican Republic", flag: "🇩🇴" },
    "EC": { tier: 2, name: "Ecuador", flag: "🇪🇨" },
    "EG": { tier: 3, name: "Egypt", flag: "🇪🇬" },
    "EE": { tier: 2, name: "Estonia", flag: "🇪🇪" },
    "FJ": { tier: 2, name: "Fiji", flag: "🇫🇯" },
    "GR": { tier: 2, name: "Greece", flag: "🇬🇷" },
    "GY": { tier: 2, name: "Guyana", flag: "🇬🇾" },
    "HK": { tier: 2, name: "Hong Kong", flag: "🇭🇰" },
    "HU": { tier: 2, name: "Hungary", flag: "🇭🇺" },
    "IS": { tier: 2, name: "Iceland", flag: "🇮🇸" },
    "IL": { tier: 2, name: "Israel", flag: "🇮🇱" },
    "KZ": { tier: 2, name: "Kazakhstan", flag: "🇰🇿" },
    "LV": { tier: 2, name: "Latvia", flag: "🇱🇻" },
    "LT": { tier: 2, name: "Lithuania", flag: "🇱🇹" },
    "MO": { tier: 2, name: "Macao", flag: "🇲🇴" },
    "MY": { tier: 2, name: "Malaysia", flag: "🇲🇾" },
    "MT": { tier: 2, name: "Malta", flag: "🇲🇹" },
    "MX": { tier: 2, name: "Mexico", flag: "🇲🇽" },
    "ME": { tier: 2, name: "Montenegro", flag: "🇲🇪" },
    "MA": { tier: 3, name: "Morocco", flag: "🇲🇦" },
    "OM": { tier: 2, name: "Oman", flag: "🇴🇲" },
    "PA": { tier: 2, name: "Panama", flag: "🇵🇦" },
    "PY": { tier: 2, name: "Paraguay", flag: "🇵🇾" },
    "PE": { tier: 2, name: "Peru", flag: "🇵🇪" },
    "PH": { tier: 2, name: "Philippines", flag: "🇵🇭" },
    "PL": { tier: 2, name: "Poland", flag: "🇵🇱" },
    "PT": { tier: 2, name: "Portugal", flag: "🇵🇹" },
    "PR": { tier: 2, name: "Puerto Rico", flag: "🇵🇷" },
    "QA": { tier: 2, name: "Qatar", flag: "🇶🇦" },
    "KR": { tier: 2, name: "Republic of Korea (South)", flag: "🇰🇷" },
    "RO": { tier: 2, name: "Romania", flag: "🇷🇴" },
    "RU": { tier: 2, name: "Russian Federation", flag: "🇷🇺" },
    "SA": { tier: 2, name: "Saudi Arabia", flag: "🇸🇦" },
    "RS": { tier: 2, name: "Serbia", flag: "🇷🇸" },
    "SG": { tier: 2, name: "Singapore", flag: "🇸🇬" },
    "SK": { tier: 2, name: "Slovakia", flag: "🇸🇰" },
    "SI": { tier: 2, name: "Slovenia", flag: "🇸🇮" },
    "ZA": { tier: 2, name: "South Africa", flag: "🇿🇦" },
    "TH": { tier: 2, name: "Thailand", flag: "🇹🇭" },
    "TR": { tier: 2, name: "Turkey", flag: "🇹🇷" },
    "UA": { tier: 2, name: "Ukraine", flag: "🇺🇦" },
    "AE": { tier: 2, name: "United Arab Emirates", flag: "🇦🇪" },
    "UY": { tier: 2, name: "Uruguay", flag: "🇺🇾" },
    "VU": { tier: 2, name: "Vanuatu", flag: "🇻🇺" },
    "VE": { tier: 2, name: "Venezuela", flag: "🇻🇪" },

    // Tier 3 Countries
    "AL": { tier: 3, name: "Albania", flag: "🇦🇱" },
    "DZ": { tier: 3, name: "Algeria", flag: "🇩🇿" },
    "AO": { tier: 3, name: "Angola", flag: "🇦🇴" },
    "AM": { tier: 3, name: "Armenia", flag: "🇦🇲" },
    "AZ": { tier: 3, name: "Azerbaijan", flag: "🇦🇿" },
    "BH": { tier: 3, name: "Bahrain", flag: "🇧🇭" },
    "BD": { tier: 3, name: "Bangladesh", flag: "🇧🇩" },
    "BB": { tier: 3, name: "Barbados", flag: "🇧🇧" },
    "BZ": { tier: 3, name: "Belize", flag: "🇧🇿" },
    "BJ": { tier: 3, name: "Benin", flag: "🇧🇯" },
    "BW": { tier: 3, name: "Botswana", flag: "🇧🇼" },
    "BF": { tier: 3, name: "Burkina Faso", flag: "🇧🇫" },
    "BI": { tier: 3, name: "Burundi", flag: "🇧🇮" },
    "KH": { tier: 3, name: "Cambodia", flag: "🇰🇭" },
    "CM": { tier: 3, name: "Cameroon", flag: "🇨🇲" },
    "CV": { tier: 3, name: "Cape Verde", flag: "🇨🇻" },
    "TD": { tier: 3, name: "Chad", flag: "🇹🇩" },
    "KM": { tier: 3, name: "Comoros", flag: "🇰🇲" },
    "CG": { tier: 3, name: "Congo", flag: "🇨🇬" },
    "SV": { tier: 3, name: "El Salvador", flag: "🇸🇻" },
    "ET": { tier: 3, name: "Ethiopia", flag: "🇪🇹" },
    "GA": { tier: 3, name: "Gabon", flag: "🇬🇦" },
    "GE": { tier: 3, name: "Georgia", flag: "🇬🇪" },
    "GT": { tier: 3, name: "Guatemala", flag: "🇬🇹" },
    "GN": { tier: 3, name: "Guinea", flag: "🇬🇳" },
    "HT": { tier: 3, name: "Haiti", flag: "🇭🇹" },
    "HN": { tier: 3, name: "Honduras", flag: "🇭🇳" },
    "IN": { tier: 3, name: "India", flag: "🇮🇳" },
    "IQ": { tier: 3, name: "Iraq", flag: "🇮🇶" },
    "JM": { tier: 3, name: "Jamaica", flag: "🇯🇲" },
    "JO": { tier: 3, name: "Jordan", flag: "🇯🇴" },
    "KE": { tier: 3, name: "Kenya", flag: "🇰🇪" },
    "KW": { tier: 3, name: "Kuwait", flag: "🇰🇼" },
    "KG": { tier: 3, name: "Kyrgyzstan", flag: "🇰🇬" },
    "LA": { tier: 3, name: "Laos", flag: "🇱🇦" },
    "LB": { tier: 3, name: "Lebanon", flag: "🇱🇧" },
    "LS": { tier: 3, name: "Lesotho", flag: "🇱🇸" },
    "MK": { tier: 3, name: "Macedonia", flag: "🇲🇰" },
    "MG": { tier: 3, name: "Madagascar", flag: "🇲🇬" },
    "ML": { tier: 3, name: "Mali", flag: "🇲🇱" },
    "MR": { tier: 3, name: "Mauritania", flag: "🇲🇷" },
    "MU": { tier: 3, name: "Mauritius", flag: "🇲🇺" },
    "MD": { tier: 3, name: "Moldova", flag: "🇲🇩" },
    "MN": { tier: 3, name: "Mongolia", flag: "🇲🇳" },
    "MZ": { tier: 3, name: "Mozambique", flag: "🇲🇿" },
    "NA": { tier: 3, name: "Namibia", flag: "🇳🇦" },
    "NI": { tier: 3, name: "Nicaragua", flag: "🇳🇮" },
    "NE": { tier: 3, name: "Niger", flag: "🇳🇪" },
    "NG": { tier: 3, name: "Nigeria", flag: "🇳🇬" },
    "PK": { tier: 3, name: "Pakistan", flag: "🇵🇰" },
    "SN": { tier: 3, name: "Senegal", flag: "🇸🇳" },
    "LK": { tier: 3, name: "Sri Lanka", flag: "🇱🇰" },
    "SR": { tier: 3, name: "Suriname", flag: "🇸🇷" },
    "SZ": { tier: 3, name: "Swaziland", flag: "🇸🇿" },
    "TJ": { tier: 3, name: "Tajikistan", flag: "🇹🇯" },
    "TZ": { tier: 3, name: "Tanzania", flag: "🇹🇿" },
    "TG": { tier: 3, name: "Togo", flag: "🇹🇬" },
    "TT": { tier: 3, name: "Trinidad and Tobago", flag: "🇹🇹" },
    "TN": { tier: 3, name: "Tunisia", flag: "🇹🇳" },
    "TM": { tier: 3, name: "Turkmenistan", flag: "🇹🇲" },
    "UG": { tier: 3, name: "Uganda", flag: "🇺🇬" },
    "UZ": { tier: 3, name: "Uzbekistan", flag: "🇺🇿" },
    "VN": { tier: 3, name: "Vietnam", flag: "🇻🇳" },
    "ZM": { tier: 3, name: "Zambia", flag: "🇿🇲" },
    "ID": { tier: 3, name: "Indonesia", flag: "🇮🇩" },
    "NP": { tier: 3, name: "Nepal", flag: "🇳🇵" },
}