import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { jwtVerify } from "jose";
import Navbar, { NavbarUser } from "@/components/Navbar";
import { db } from "@/db";
import { users } from "@/db/schema";
import { eq } from "drizzle-orm";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const secret = new TextEncoder().encode(process.env.SESSION_SECRET!);

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let user: NavbarUser | null = null;


  try {
    const session = (await cookies()).get("session")

    if (session) {
      const { payload } = await jwtVerify(session.value, secret)
      const uid = payload.uid as string;

      const result = await db
        .select({
          email: users.email,
          avatarUrl: users.avatarUrl,
          name: users.name
        })
        .from(users)
        .where(eq(users.firebaseUid, uid))
        .limit(1)

      if (result.length > 0) {
        user = result[0];
      }

    }


  } catch {
    user = null
  }


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar user={user} />
        {children}
      </body>
    </html>
  );
}
